apiVersion: v1
kind: Service
metadata:
  name: flink-master
  annotations:
    # Тип балансировщика: внутренний.
    yandex.cloud/load-balancer-type: internal
    # Идентификатор подсети, в которой необходимо выделить IP-адрес для внутреннего сетевого балансировщика нагрузки.
    yandex.cloud/subnet-id: e9b01mfn1tqe08ogu5po
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: user-interface
    - port: 6123
      name: rpc
    - port: 6124
      name: blob
    - port: 6125
      name: query
  selector:
    app: flink
    component: master
  loadBalancerIP: 172.27.15.18
  type: LoadBalancer