apiVersion: v1
kind: Service
metadata:
  name: flink-master
spec:
  ports:
    - port: 8081
      name: ui
    - port: 6123
      name: rpc
    - port: 6124
      name: blob
    - port: 6125
      name: query
  selector:
    app: flink
    component: master