apiVersion: v1
kind: Service
metadata:
  name: flink-api
  annotations:
    # Тип балансировщика: внутренний.
    yandex.cloud/load-balancer-type: internal
    # Идентификатор подсети, в которой необходимо выделить IP-адрес для внутреннего сетевого балансировщика нагрузки.
    yandex.cloud/subnet-id: e9b01mfn1tqe08ogu5po
spec:
  ports:
    - port: 8083
      targetPort: 8083
      name: rest-api
    - port: 6123
      name: rpc
    - port: 6124
      name: blob
    - port: 6125
      name: query
  selector:
    app: flink
    component: rest
  type: LoadBalancer