apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: worker
  template:
    metadata:
      labels:
        app: flink
        component: worker
    spec:
      containers:
        - name: worker
          image: flink:1.17-scala_2.12-java11
          args:
            - taskmanager
          ports:
              - containerPort: 6121
                name: data
              - containerPort: 6122
                name: rpc
              - containerPort: 6125
                name: query
          env:
#            - name: JOB_MANAGER_RPC_ADDRESS
#              value: flink-master
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: flink-master
                sql-gateway.endpoint.rest.address: 0.0.0.0
                sql-gateway.session.idle-timeout: 1
                sql-gateway.worker.keepalive-time: 1
                rest.address: flink-master
                taskmanager.numberOfTaskSlots: 20
                taskmanager.memory.process.size: 4g
                jobmanager.memory.process.size: 2g
                execution.checkpointing.interval: 30s
                execution.checkpointing.mode: EXACTLY_ONCE