version: 2

sources:
  - name: shipment
    tables:
      - name: shipments
        config:
#          type: view
          connector_properties:
            connector: 'postgres-cdc'
            hostname: 'postgres'
            port: '5432'
            username: 'postgres'
            password: 'postgres'
            database-name: 'postgres'
            schema-name: 'public'
            slot.name: 'fuck'
            decoding.plugin.name: 'pgoutput'
            table-name: 'shipments'
#          watermark:
#            column: event_timestamp
#            strategy: event_timestamp
        columns:
          - name: shipment_id
            data_type: INT
          - name: order_id
            data_type: INT
          - name: origin
            data_type: STRING
          - name: destination
            data_type: STRING
          - name: is_arrived
            data_type: BOOLEAN